package es.uma.informatica.sii.proyecto;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AperturaCuentaPooledIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void aperturaCuentaPooledIT() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.manage().window().setSize(new Dimension(976, 1040));
    driver.findElement(By.linkText("pulse aqui")).click();
    driver.findElement(By.id("loginAdmin:user")).click();
    driver.findElement(By.id("loginAdmin:user")).sendKeys("ponciano");
    driver.findElement(By.id("loginAdmin:pass")).click();
    driver.findElement(By.id("loginAdmin:pass")).sendKeys("ponciano");
    driver.findElement(By.id("loginAdmin:botonLogin")).click();
    driver.findElement(By.id("cuentas")).click();
    driver.findElement(By.cssSelector("#headingTwo > .accordion-button")).click();
    driver.findElement(By.id("botonAbrirPooled")).click();
    driver.findElement(By.id("abrirPooled:cliente")).click();
    driver.findElement(By.id("abrirPooled:cliente")).sendKeys("556677E");
    driver.findElement(By.id("abrirPooled:iban")).click();
    driver.findElement(By.id("abrirPooled:iban")).sendKeys("ES55667");
    driver.findElement(By.id("abrirPooled:swift")).click();
    driver.findElement(By.id("abrirPooled:swift")).sendKeys("5678");
    driver.findElement(By.id("abrirPooled:comision")).click();
    driver.findElement(By.id("abrirPooled:comision")).sendKeys("0.1");
    driver.findElement(By.id("abrirPooled:ibanReferencia")).click();
    driver.findElement(By.id("abrirPooled:ibanReferencia")).sendKeys("HN47QUXH11325678769785549996");
    driver.findElement(By.id("abrirPooled:boton")).click();
    driver.findElement(By.cssSelector("#headingTwo > .accordion-button")).click();
    driver.findElement(By.cssSelector("#pol tr:nth-child(1) > td:nth-child(1)")).click();
    assertThat(driver.findElement(By.id("pol:j_idt38:0:textoIBAN")).getText(), is("ES55667"));
  }
}
