package es.uma.informatica.sii.proyecto;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
public class BloquearEmpresaIITT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  
  private String baseURL;
  private static Map<String, String> propiedadesExtra = new HashMap<>();
  
  @BeforeClass
  public void setupClass() {
	  String server = "localhost";
	  try(InputStream is = BloquearIndividualIT.class.getClassLoader().getResourceAsStream("pom.properties")){
		  Properties pomProperties = new Properties();
		  pomProperties.load(is);
		  server=pomProperties.getProperty("server.host");
		  String databaseURL = "jdbc:mysql://"+server+":3306/sii";
		  propiedadesExtra.put("javax.persistence.jdbc.url", databaseURL);
	  }catch(IOException e) {
		  e.printStackTrace();
	  }
	  baseURL = "http://"+server+":8080/trazabilidad-war/";
  }
  
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void bloquearEmpresa() {
    driver.get(baseURL);
    driver.manage().window().setSize(new Dimension(976, 1040));
    driver.findElement(By.linkText("pulse aqui")).click();
    driver.findElement(By.id("loginAdmin:user")).click();
    driver.findElement(By.id("loginAdmin:pass")).click();
    driver.findElement(By.id("loginAdmin:user")).click();
    driver.findElement(By.id("loginAdmin:user")).sendKeys("ponciano");
    driver.findElement(By.id("loginAdmin:pass")).click();
    driver.findElement(By.id("loginAdmin:pass")).sendKeys("ponciano");
    driver.findElement(By.id("loginAdmin:botonLogin")).click();
    driver.findElement(By.id("clientesEmpresas")).click();
    driver.findElement(By.id("formulario:j_idt6:0:botonBloq")).click();
    driver.findElement(By.id("formulario:j_idt6:0:textoEstado")).click();
    assertThat(driver.findElement(By.id("formulario:j_idt6:0:textoEstado")).getText(), is("bloqueado"));
  }
}
