package es.uma.informatica.sii.proyecto;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PilotechIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void aadirAutorizadosIT() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.findElement(By.linkText("pulse aqui")).click();
    driver.findElement(By.id("loginAdmin:user")).click();
    driver.findElement(By.id("loginAdmin:user")).sendKeys("ponciano");
    driver.findElement(By.id("loginAdmin:pass")).click();
    driver.findElement(By.id("loginAdmin:pass")).sendKeys("ponciano");
    driver.findElement(By.id("loginAdmin:botonLogin")).click();
    driver.findElement(By.id("pa")).click();
    driver.findElement(By.id("botonAltaAut")).click();
    driver.findElement(By.id("altaAutorizado:nombre")).click();
    driver.findElement(By.id("altaAutorizado:nombre")).sendKeys("Pepe");
    driver.findElement(By.id("altaAutorizado:apellido")).click();
    driver.findElement(By.id("altaAutorizado:apellido")).sendKeys("Ramirez Perez");
    driver.findElement(By.id("altaAutorizado:fechaNacimiento")).click();
    driver.findElement(By.id("altaAutorizado:fechaNacimiento")).sendKeys("1987-04-14");
    driver.findElement(By.id("altaAutorizado:identificacion")).click();
    driver.findElement(By.id("altaAutorizado:identificacion")).sendKeys("12345634V");
    driver.findElement(By.id("altaAutorizado:direccion")).click();
    driver.findElement(By.id("altaAutorizado:direccion")).sendKeys("C/Benalmadena nº40");
    driver.findElement(By.id("altaAutorizado:user")).click();
    driver.findElement(By.id("altaAutorizado:user")).sendKeys("pepe_12");
    driver.findElement(By.id("altaAutorizado:pass")).click();
    driver.findElement(By.id("altaAutorizado:pass")).sendKeys("pepe_12");
    driver.findElement(By.id("altaAutorizado:botonAltaAutorizado")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).click();
    assertThat(driver.findElement(By.id("formulario:j_idt16:0:textoIdentificacion")).getText(), is("12345634V"));
  }
  @Test
  public void modificarAutorizadosIT() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.findElement(By.linkText("pulse aqui")).click();
    driver.findElement(By.id("loginAdmin:user")).click();
    driver.findElement(By.id("loginAdmin:user")).sendKeys("ponciano");
    driver.findElement(By.id("loginAdmin:pass")).click();
    driver.findElement(By.id("loginAdmin:pass")).sendKeys("ponciano");
    driver.findElement(By.id("loginAdmin:botonLogin")).click();
    driver.findElement(By.id("pa")).click();
    driver.findElement(By.id("formulario:j_idt16:1:botonMod")).click();
    driver.findElement(By.id("modAutorizado:nombre")).click();
    driver.findElement(By.id("modAutorizado:nombre")).sendKeys("Juan");
    driver.findElement(By.id("modAutorizado:botonModificarAut")).click();
    driver.findElement(By.id("formulario:j_idt16:1:textoNombre")).click();
    assertThat(driver.findElement(By.id("formulario:j_idt16:1:textoNombre")).getText(), is("Juan"));
  }
  @Test
  public void eliminarAutorizadosIT() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.findElement(By.linkText("pulse aqui")).click();
    driver.findElement(By.id("loginAdmin:user")).click();
    driver.findElement(By.id("loginAdmin:user")).sendKeys("ponciano");
    driver.findElement(By.id("loginAdmin:pass")).click();
    driver.findElement(By.id("loginAdmin:pass")).sendKeys("ponciano");
    driver.findElement(By.id("loginAdmin:botonLogin")).click();
    driver.findElement(By.id("pa")).click();
    driver.findElement(By.id("formulario:j_idt16:0:botonBaja")).click();
    driver.findElement(By.id("formulario:j_idt16:0:textoEstado2")).click();
    assertThat(driver.findElement(By.id("formulario:j_idt16:0:textoEstado2")).getText(), is("baja"));
  }
  @Test
  public void bloquearClientesIT() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.findElement(By.linkText("pulse aqui")).click();
    driver.findElement(By.id("loginAdmin:user")).click();
    driver.findElement(By.id("loginAdmin:user")).sendKeys("ponciano");
    driver.findElement(By.id("loginAdmin:pass")).click();
    driver.findElement(By.id("loginAdmin:pass")).sendKeys("ponciano");
    driver.findElement(By.id("loginAdmin:botonLogin")).click();
    driver.findElement(By.id("clientesIndividuales")).click();
    driver.findElement(By.id("formulario:j_idt16:0:botonBloq")).click();
    driver.findElement(By.id("formulario:j_idt16:0:textoEstado3")).click();
    assertThat(driver.findElement(By.id("formulario:j_idt16:0:textoEstado3")).getText(), is("bloqueado"));
  }
  @Test
  public void bloquearAutorizadoIT() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.findElement(By.linkText("pulse aqui")).click();
    driver.findElement(By.id("loginAdmin:user")).click();
    driver.findElement(By.id("loginAdmin:user")).sendKeys("ponciano");
    driver.findElement(By.id("loginAdmin:pass")).click();
    driver.findElement(By.id("loginAdmin:pass")).sendKeys("ponciano");
    driver.findElement(By.id("loginAdmin:botonLogin")).click();
    driver.findElement(By.id("pa")).click();
    driver.findElement(By.id("formulario:j_idt16:1:botonBloq")).click();
    driver.findElement(By.id("formulario:j_idt16:1:textoEstado3")).click();
    assertThat(driver.findElement(By.id("formulario:j_idt16:1:textoEstado3")).getText(), is("bloqueado"));
  }
  @Test
  public void desbloquearClienteIT() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.findElement(By.linkText("pulse aqui")).click();
    driver.findElement(By.id("loginAdmin:user")).click();
    driver.findElement(By.id("loginAdmin:user")).sendKeys("ponciano");
    driver.findElement(By.id("loginAdmin:pass")).click();
    driver.findElement(By.id("loginAdmin:pass")).sendKeys("ponciano");
    driver.findElement(By.id("loginAdmin:botonLogin")).click();
    driver.findElement(By.id("clientesIndividuales")).click();
    driver.findElement(By.id("formulario:j_idt16:0:botonDesbloq")).click();
    driver.findElement(By.cssSelector("td:nth-child(6)")).click();
    assertThat(driver.findElement(By.id("formulario:j_idt16:0:textoEstado1")).getText(), is("activo"));
  }
  @Test
  public void desbloquearAutorizadoIT() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.findElement(By.linkText("pulse aqui")).click();
    driver.findElement(By.id("loginAdmin:user")).click();
    driver.findElement(By.id("loginAdmin:user")).sendKeys("ponciano");
    driver.findElement(By.id("loginAdmin:pass")).click();
    driver.findElement(By.id("loginAdmin:pass")).sendKeys("ponciano");
    driver.findElement(By.id("loginAdmin:botonLogin")).click();
    driver.findElement(By.id("pa")).click();
    driver.findElement(By.id("formulario:j_idt16:1:botonDesbloq")).click();
    driver.findElement(By.id("formulario:j_idt16:1:textoEstado1")).click();
    assertThat(driver.findElement(By.id("formulario:j_idt16:1:textoEstado1")).getText(), is("activo"));
  }
  @Test
  public void cambioDivisaClienteIT() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.findElement(By.id("login:user")).click();
    driver.findElement(By.id("login:user")).sendKeys("juan");
    driver.findElement(By.id("login:pass")).click();
    driver.findElement(By.id("login:pass")).sendKeys("juan");
    driver.findElement(By.id("login:botonLogin")).click();
    driver.findElement(By.id("formulario2:j_idt34:0:cambioDivisa")).click();
    driver.findElement(By.id("cambiarDivisaCA:dd")).click();
    {
      WebElement dropdown = driver.findElement(By.id("cambiarDivisaCA:dd"));
      dropdown.findElement(By.xpath("//option[. = 'dolares']")).click();
    }
    driver.findElement(By.id("cambiarDivisaCA:cantidad")).click();
    driver.findElement(By.id("cambiarDivisaCA:cantidad")).sendKeys("10.0");
    driver.findElement(By.id("cambiarDivisaCA:sesion1")).click();
    driver.findElement(By.cssSelector(".h2:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector(".h2:nth-child(1)")).getText(), is("CUENTAS SEGREGADAS"));
  }
  @Test
  public void cambioDivisaAdminIT() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.findElement(By.linkText("pulse aqui")).click();
    driver.findElement(By.id("loginAdmin:user")).click();
    driver.findElement(By.id("loginAdmin:user")).sendKeys("ponciano");
    driver.findElement(By.id("loginAdmin:pass")).click();
    driver.findElement(By.id("loginAdmin:pass")).sendKeys("ponciano");
    driver.findElement(By.id("loginAdmin:botonLogin")).click();
    driver.findElement(By.id("cuentas")).click();
    driver.findElement(By.cssSelector("#headingTwo > .accordion-button")).click();
    driver.findElement(By.id("pol:j_idt38:0:cambioDivisa")).click();
    driver.findElement(By.id("cambiarDivisaA:dd")).click();
    {
      WebElement dropdown = driver.findElement(By.id("cambiarDivisaA:dd"));
      dropdown.findElement(By.xpath("//option[. = 'dolares']")).click();
    }
    driver.findElement(By.id("cambiarDivisaA:cantidad")).click();
    driver.findElement(By.id("cambiarDivisaA:cantidad")).sendKeys("10.0");
    driver.findElement(By.id("cambiarDivisaA:sesion2")).click();
    driver.findElement(By.cssSelector(".display-3")).click();
    assertThat(driver.findElement(By.cssSelector(".display-3")).getText(), is("CUENTAS"));
  }
  @Test
  public void altaClienteFisicoIT() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.findElement(By.linkText("pulse aqui")).click();
    driver.findElement(By.id("loginAdmin:user")).click();
    driver.findElement(By.id("loginAdmin:user")).sendKeys("ponciano");
    driver.findElement(By.id("loginAdmin:pass")).click();
    driver.findElement(By.id("loginAdmin:pass")).sendKeys("ponciano");
    driver.findElement(By.id("loginAdmin:botonLogin")).click();
    driver.findElement(By.id("clientesIndividuales")).click();
    driver.findElement(By.id("botonAltaIndividual")).click();
    driver.findElement(By.id("altaIndividual:nombre")).click();
    driver.findElement(By.id("altaIndividual:nombre")).sendKeys("Juan Jesus");
    driver.findElement(By.cssSelector(".col-md-4:nth-child(3)")).click();
    driver.findElement(By.id("altaIndividual:apellido")).click();
    driver.findElement(By.id("altaIndividual:apellido")).sendKeys("Moreno");
    driver.findElement(By.id("altaIndividual:fechaNacimiento")).click();
    driver.findElement(By.id("altaIndividual:fechaNacimiento")).sendKeys("2000-05-23");
    driver.findElement(By.id("altaIndividual:identificacion")).click();
    driver.findElement(By.id("altaIndividual:identificacion")).sendKeys("12376423N");
    driver.findElement(By.id("altaIndividual:direccion")).click();
    driver.findElement(By.id("altaIndividual:direccion")).sendKeys("C/Pepin Lora");
    driver.findElement(By.id("altaIndividual:ciudad")).click();
    driver.findElement(By.id("altaIndividual:ciudad")).sendKeys("Malaga");
    driver.findElement(By.id("altaIndividual:pais")).click();
    driver.findElement(By.id("altaIndividual:pais")).sendKeys("España");
    driver.findElement(By.id("altaIndividual:cp")).click();
    driver.findElement(By.id("altaIndividual:cp")).sendKeys("29001");
    driver.findElement(By.id("altaIndividual:user")).click();
    driver.findElement(By.id("altaIndividual:user")).sendKeys("juanje");
    driver.findElement(By.id("altaIndividual:pass")).click();
    driver.findElement(By.id("altaIndividual:pass")).sendKeys("juanje");
    driver.findElement(By.id("altaIndividual:botonAltaIndividual")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).click();
    assertThat(driver.findElement(By.id("formulario:j_idt16:0:textoIdentificacion")).getText(), is("12376423N"));
  }
  @Test
  public void altaClienteJuridicoIT() {
    driver.get("http://localhost:8080/proyecto-war/");
    driver.findElement(By.linkText("pulse aqui")).click();
    driver.findElement(By.id("loginAdmin:user")).click();
    driver.findElement(By.id("loginAdmin:user")).sendKeys("ponciano");
    driver.findElement(By.id("loginAdmin:pass")).click();
    driver.findElement(By.id("loginAdmin:pass")).sendKeys("ponciano");
    driver.findElement(By.id("loginAdmin:botonLogin")).click();
    driver.findElement(By.id("clientesEmpresas")).click();
    driver.findElement(By.id("botonAltaEmpresa")).click();
    driver.findElement(By.id("altaEmpresa:identificacion")).click();
    driver.findElement(By.id("altaEmpresa:identificacion")).sendKeys("45678912M");
    driver.findElement(By.id("altaEmpresa:razonSocial")).click();
    driver.findElement(By.id("altaEmpresa:razonSocial")).sendKeys("Sociedad");
    driver.findElement(By.id("altaEmpresa:direccion")).click();
    driver.findElement(By.id("altaEmpresa:direccion")).sendKeys("C/Santiago nº25");
    driver.findElement(By.id("altaEmpresa:ciudad")).click();
    driver.findElement(By.id("altaEmpresa:ciudad")).sendKeys("Malaga");
    driver.findElement(By.id("altaEmpresa:pais")).click();
    driver.findElement(By.id("altaEmpresa:pais")).sendKeys("España");
    driver.findElement(By.id("altaEmpresa:cp")).click();
    driver.findElement(By.id("altaEmpresa:cp")).sendKeys("29015");
    driver.findElement(By.id("altaEmpresa:botonAltaEmpresa")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).click();
    assertThat(driver.findElement(By.id("formulario:j_idt19:0:textoIdentificacion")).getText(), is("45678912M"));
  }
}
